apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  type: NodePort
  selector:
    app: chat-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080  # Pick a port between 30000-32767

# used nodeport cos im not allowed to use loadbalancer
